version: "3.9"

services:

  mongo: 
    image: mongo:latest
    container_name: mongoContainer
    env_file:
      - .env
    ports: 
      - "27017:27017"
    networks:
      - linkcanopy-network

  backend:
    build: ./backend
    container_name: linkcanopy-backend
    env_file:
      - ./backend/.env
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
    networks: 
      - linkcanopy-network
      
  frontend:
    build: ./frontend
    container_name: linkcanopy-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - linkcanopy-network
    
networks:
  linkcanopy-network:
    driver: bridge
        